name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: CI
    uses: Ren-Nice/reusable-workflows/.github/workflows/reusable-build.yml
    with:
        dotnet_version: 9.0.x