name: PR Verify

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: PR Verify
    uses: Ren-Nice/reusable-workflows/.github/workflows/reusable-build.yml
    with:
        dotnet_version: 9.0.x